### PR TITLE
Don't allow creating downtimes with flexible duration `0h0m`

### LINKED ISSUE #765: Creating downtime with flexible duration `0h0m` are possible
## Describe the bug
Creating downtime with flexible duration `0h0m` should not be possible.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #765

Blocked by: Icinga/ipl-html#122

### CODE REVIEW

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 1]
```diff
@@ -182,7 +182,19 @@ protected function assembleElements()
                     'required'  => true,
                     'label'     => t('Duration'),
                     'value'     => $this->flexibleDuration->h,
-                    'min'       => 0
+                    'min'       => 0,
+                    'validators' => [
+                        'Callback' => function ($value, $validator) {
+                            /** @var CallbackValidator $validator */
+
+                            if ($this->getValue('minutes') == 0 && $value == 0) {
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:190]: are these non-strict comparisons for a reason?

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 2]
```diff
@@ -182,7 +182,19 @@ protected function assembleElements()
...
+                                $validator->addMessage(t('The duration must be at least one minute'));
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:191]: No, it must not be zero.

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 3]
```diff
@@ -192,19 +204,24 @@ protected function assembleElements()
                 'number',
                 'minutes',
                 [
-                    'required'  => true,
-                    'value'     => $this->flexibleDuration->m,
-                    'min'       => 0
+                    'required'   => true,
+                    'value'      => $this->flexibleDuration->m,
+                    'min'        => 0
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:209]: Please revert this. Why or what did this anyway?

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 4]
```diff
@@ -192,19 +204,24 @@ protected function assembleElements()
...
                 new HtmlElement('label', null, new HtmlElement('span', null, Text::create(t('Minutes'))))
             );
 
-            $hoursInput->getWrapper()
-                ->add($minutesInput)
-                ->getAttributes()->add('class', 'downtime-duration');
+            $hoursInput->getWrapper()->on(
+                IcingaFormDecorator::ON_ASSEMBLED,
+                function ($hoursInput) use ($minutesInput, $decorator) {
+                    $hoursInput->insertAfter($minutesInput, $this->getElement('hours'))
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:220]: Instead of using `getElement` please pass through `$hoursInput`.

**Review by nilmerg — CHANGES_REQUESTED** [review]
Please create your own commit. Most of it is your work after all.

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 5]
```diff
@@ -192,19 +204,25 @@ protected function assembleElements()
                 'number',
                 'minutes',
                 [
-                    'required'  => true,
-                    'value'     => $this->flexibleDuration->m,
-                    'min'       => 0
+                    'required' => true,
+                    'value'    => $this->flexibleDuration->m,
+                    'min'      => 0
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:209]: Not sure what you're doing here, the indentation was previously (without your changes) already correct.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
