### PR TITLE
Fix view mode switcher shows different mode than what is used

### LINKED ISSUE #489: View mode switcher shows different mode than what is used
## Describe the bug
View mode switcher shows different mode than what is used.

## To Reproduce
Go to a view with a mode switcher, add `view=...` with a different mode to the url.

## Expected behavior
The mode switcher shows the view mode as active that is actually in use.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fix #489

### CODE REVIEW

File: library/Icingadb/Web/Controller.php [hunk 1]
```diff
@@ -367,7 +367,7 @@ public function createViewModeSwitcher(
         LimitControl $limitControl,
         bool $verticalPagination = false
     ): ViewModeSwitcher {
-        $viewModeSwitcher = new ViewModeSwitcher();
+        $viewModeSwitcher = new ViewModeSwitcher(Url::fromRequest());
```
Comment (nilmerg) [inline library/Icingadb/Web/Controller.php:370]: It doesn't need to parse the url to know the current view mode, it's already passed by `populate`, just not accessed internally.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: library/Icingadb/Web/Control/ViewModeSwitcher.php [hunk 2]
```diff
@@ -101,7 +101,13 @@ public function setViewModeParam(string $viewModeParam): self
      */
     public function getViewMode(): string
     {
-        return $this->getValue($this->getViewModeParam(), $this->getDefaultViewMode());
+        $viewMode =  $this->getPopulatedValue($this->getViewModeParam(), $this->getDefaultViewMode());
```
Comment (nilmerg) [inline library/Icingadb/Web/Control/ViewModeSwitcher.php:104]: There's a superfluous space after the equal sign.

**Review by nilmerg — APPROVED** [review]
