### PR TITLE
ApiTransportForm: Don't use text to create password elements

### LINKED ISSUE #459: Command transport passwordfield always show the password (aka is not a password field)
## Describe the bug
Command transport passwordfield always show the password

## To Reproduce
Configure a command transport, the api password is always shown. Other password fields hide the password

## Expected behavior
The password should be also hidden like all other password fields in icingaweb2

## Screenshots
grafik

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc2
* Icinga Web 2 version (System - About): 2.9.4
* Web browser: FireFox, Chrome, whatever
* Icinga 2 version (`icinga2 --version`): 2.13.2-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc2-dev
* PHP version used (`php --version`): 8.0.12
* Server operating system and version: CentOS Linux 8

### PR DESCRIPTION
**Pull request by yhabteab**
resolves #459

### CODE REVIEW

**Comment by yhabteab** [comment]
Blocked By

- https://github.com/Icinga/ipl-html/pull/57

**Comment by yhabteab** [comment]
@cla-bot check

File: application/forms/ApiTransportForm.php [hunk 1]
```diff
@@ -49,8 +49,7 @@ protected function assemble()
             'description'   => t('User to authenticate with using HTTP Basic Auth')
         ]);
 
-        // TODO: Use a password element
-        $this->addElement('text', 'password', [
+        $this->addElement('password', 'password', [
             'required'      => true,
             'label'         => t('API Password')
```
Comment (nilmerg) [inline application/forms/ApiTransportForm.php:54]: We should probably add `autocomplete=new-password` here. (https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password)

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
