### PR TITLE
(AddComment/AcknowledgeProblem)Form: Add validators to `expire_time` element

### LINKED ISSUE #764: Comments with expiration date in the past are possible
## Describe the bug
It should not be possible to create a comment whose expiration time is in the past.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #764

### CODE REVIEW

File: application/forms/Command/Object/AddCommentForm.php [hunk 1]
```diff
@@ -108,7 +109,19 @@ protected function assembleElements()
...
                     'value'                     => $expireTime,
                     'label'                     => t('Expire Time'),
-                    'description'               => t('Choose the date and time when Icinga should delete the comment.')
+                    'description'               => t('Choose the date and time when Icinga should delete the comment.'),
+                    'validators'                => [
+                        'DateTime' => ['break_chain_on_failure' => true],
+                        'Callback' => function ($value, $validator) {
+                            /** @var CallbackValidator $validator */
+                            if ($value <= (new DateTime())) {
+                                $validator->addMessage(t('Comment expire time must not be in the past'));
```
Comment (nilmerg) [inline application/forms/Command/Object/AddCommentForm.php:118]: ~~Comment~~The

**Review by nilmerg — CHANGES_REQUESTED** [review]
Might this also be necessary for the acknowledgement form?

**Review by nilmerg — APPROVED** [review]
