### PR TITLE
Preserve filters after clicking `Load More`

### LINKED ISSUE #590: History load more doesn't preserve filters
## Describe the bug
Filtering the history and clicking load more, shows unfiltered results on page no. 2.

## Expected behavior
Page no. 2 and further are filtered.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): master

### PR DESCRIPTION
**Pull request by raviks789**
Currently, the load more urls are fixed and hence the filters are not preserved after clicking on load more.
In this fix load more url has been changed dynamically upon applying filters for history or notifications and
hence preserving the filters.

fixes #590

### CODE REVIEW

**Review by nilmerg — CHANGES_REQUESTED** [review]
* Define a filter and reload the page or column. The load more url is now missing the filter. (Worked previously)
* Define a filter and click on load more once. A second click on load more returns unfiltered results again.

File: application/controllers/HistoryController.php [hunk 1]
```diff
@@ -65,6 +66,7 @@ public function indexAction()
             }
         } else {
             $filter = $searchBar->getFilter();
+            $url->setQueryString(QueryString::render($filter));
```
[the remark this answers is not in the document]
Comment (nilmerg) [reply application/controllers/HistoryController.php:69]: Also, `$url` gets some params applied when it's initialized. They're overridden here. These are params like `limit` for example, which are now lost and not transferred to the load more url anymore.

I reckon that has been intentional (:wink:) and only one fact has been forgotten: When submitting the search bar, filters are not part of `$this->params`. If the search bar is not sent, they are though. So, to fix this, I guess you need one of your conditions back (if hasBeenSent) and then apply `$filter` in a way that doesn't override other params.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: application/controllers/HistoryController.php [hunk 2]
```diff
@@ -49,11 +50,15 @@ public function indexAction()
             ]
         );
         $viewModeSwitcher = $this->createViewModeSwitcher($paginationControl, $limitControl, true);
-        $searchBar = $this->createSearchBar($history, [
+        $preserveParams = [
```
Comment (nilmerg) [inline application/controllers/HistoryController.php:53]: The actions have all their specific structure:

* Init (params, auth, tabs)
* get db
* setup query
* setup controls
* handle controls
* apply filters
* export
* register controls
* register content

So initializing `$preserveParams` should be at the top and `createSearchBar` where it has been.

File: application/controllers/HistoryController.php [hunk 3]
```diff
@@ -49,11 +50,15 @@ public function indexAction()
...
             $limitControl->getLimitParam(),
             $sortControl->getSortParam(),
             $viewModeSwitcher->getViewModeParam()
-        ]);
+        ];
+
+
+        $searchBar = $this->createSearchBar($history, $preserveParams);
+        $url = $url->onlyWith($preserveParams);
```
Comment (nilmerg) [inline application/controllers/HistoryController.php:61]: You should put that to the same place where the query string is handled. Well, why not even put it right above where it's required. (Around line no. 103) You might even move the initialization of `$url` there as well. To shorten everything a bit:

```
$url = Url::fromRequest()->onlyWith...
$url->setQueryString(QueryString::render(...
```

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
