### PR TITLE
Fix that custom variables with dots in their name are broken

### LINKED ISSUE #1001: Custom variables with dots in their names are broken again
## Describe the bug
```
Cannot join relation "foo" in model Icinga\Module\Icingadb\Model\Vars. Relation not found.

#0 [internal function]: ipl\Orm\Resolver->resolveRelations(String)
#1 /usr/local/src/ipl-orm/src/Compat/FilterProcessor.php(111): AppendIterator->next()
#2 /usr/local/src/ipl-orm/src/Compat/FilterProcessor.php(185): ipl\Orm\Compat\FilterProcessor->requireAndResolveFilterColumns(Object(ipl\Stdlib\Filter\Unequal), Object(ipl\Orm\Query), NULL)
#3 /usr/local/src/ipl-orm/src/Compat/FilterProcessor.php(80): ipl\Orm\Compat\FilterProcessor->requireAndResolveFilterColumns(Object(ipl\Stdlib\Filter\All), Object(ipl\Orm\Query))
#4 /usr/local/src/ipl-orm/src/Query.php(477): ipl\Orm\Compat\FilterProcessor::resolveFilter(Object(ipl\Stdlib\Filter\All), Object(ipl\Orm\Query))
#5 /usr/local/src/ipl-orm/src/Query.php(698): ipl\Orm\Query->assembleSelect()
#6 /usr/local/src/ipl-orm/src/ResultSet.php(142): ipl\Orm\Query->yieldResults()
#7 [internal function]: ipl\Orm\ResultSet->yieldTraversable(Object(Generator))
#8 /usr/local/src/ipl-orm/src/ResultSet.php(122): Generator->valid()
#9 /usr/local/src/ipl-orm/src/ResultSet.php(69): ipl\Orm\ResultSet->advance()
#10 /usr/local/src/ipl-orm/src/Query.php(671): ipl\Orm\ResultSet->current()
#11 /usr/share/icingaweb2-modules/icingadb/application/controllers/HostsController.php(124): ipl\Orm\Query->first()
#12 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Web/Controller.php(470): Icinga\Module\Icingadb\Controllers\HostsController->indexAction()
#13 /icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#14 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /icingaweb2/library/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#17 /icingaweb2/public/index.php(4): require_once(String)
#18 {main}
```

## To Reproduce
`hosts?host.vars.foo.bar!=oof`

## Expected behavior
No stacktrace.

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #1001
requires https://github.com/Icinga/ipl-orm/pull/133

### CODE REVIEW

File: library/Icingadb/Model/Behavior/FlattenedObjectVars.php [hunk 1]
```diff
@@ -66,6 +54,8 @@ public function set($name, $value)
             // the condition refer to a different column, which is totally irrelevant, but since it's always the same
             // column, the FilterProcessor won't attempt to combine the conditions. The literal icing on the cake.
             $condition->setColumn('always_the_same_but_totally_irrelevant');
+
+            return $condition;
```
Comment (yhabteab) [inline library/Icingadb/Model/Behavior/FlattenedObjectVars.php:58]: Since you're actually returning a *transformed* filter condition now, is the above workaround still required?
```php
$condition->setColumn('always_the_same_but_totally_irrelevant');
```

Comment (nilmerg) [reply library/Icingadb/Model/Behavior/FlattenedObjectVars.php:58]: Yes, the column name still doesn't change. The processor would then think that `host.vars.foo` and `host.vars.bar` are two different cols, although both translate `foo|bar` to `flatname=foo|flatname=bar`.

Comment (yhabteab) [reply library/Icingadb/Model/Behavior/FlattenedObjectVars.php:58]: > Yes, the column name still doesn't change.

However, this workaround is justified by not returning a transformed filter, which is no longer the case, and I see no difference between with and without this workaround, **both are broken**.

Filter: `service.vars.mixed_list[*]~bar|service.vars.mixed_list[*]~test`

**With "always_the_same_but_totally_irrelevant"**:
```sql
SELECT sub_customvar_flat_service.id AS sub_customvar_flat_service_id
FROM customvar_flat sub_customvar_flat
       INNER JOIN service_customvar sub_customvar_flat_service_customvar
                  ON sub_customvar_flat_service_customvar.customvar_id = sub_customvar_flat.customvar_id
       INNER JOIN service sub_customvar_flat_service
                  ON sub_customvar_flat_service.id = sub_customvar_flat_service_customvar.service_id
WHERE (sub_customvar_flat.flatname = 'mixed_list%5B%2A%5D')
  AND (sub_customvar_flat.flatvalue = 'bar|service.vars.mixed_list%5B%2A%5D~test')
```

**Without:**
```sql
SELECT sub_customvar_flat_service.id AS sub_customvar_flat_service_id
FROM customvar_flat sub_customvar_flat
       INNER JOIN service_customvar sub_customvar_flat_service_customvar
                  ON sub_customvar_flat_service_customvar.customvar_id = sub_customvar_flat.customvar_id
       INNER JOIN service sub_customvar_flat_service
                  ON sub_customvar_flat_service.id = sub_customvar_flat_service_customvar.service_id
WHERE (sub_customvar_flat.flatname = 'mixed_list%5B%2A%5D')
  AND (sub_customvar_flat.flatvalue = 'bar|service.vars.mixed_list%5B%2A%5D~test')
```

Comment (nilmerg) [reply library/Icingadb/Model/Behavior/FlattenedObjectVars.php:58]: Works for me. How do you test this?

Comment (nilmerg) [reply library/Icingadb/Model/Behavior/FlattenedObjectVars.php:58]: And: By *transforming* the change of the condition type is meant. Which still isn't the case.

**Review by yhabteab — APPROVED** [review]
