### PR TITLE
Show a notification for every successful action

### LINKED ISSUE #272: Doesn't show success messages when removing/creating `ACK/DT` & `Comments`
## Describe the bug
No success messages are displayed as the monitoring module does, when creating/removing `ACK`, `DT` and `Comments`.

### PR DESCRIPTION
**Pull request by Yonas-net**
resolves #272

### CODE REVIEW

File: application/controllers/CommandTransportController.php [hunk 1]
```diff
@@ -64,6 +65,8 @@ public function showAction()
                 Filter::where('name', $transportName)
             );
 
+            Notification::success(sprintf(t('Command transport "%s" updated successfully'), $transportName));
```
Comment (nilmerg) [inline application/controllers/CommandTransportController.php:68]: `Updated command transport "%s" successfully`

File: application/controllers/CommandTransportController.php [hunk 2]
```diff
@@ -80,6 +83,9 @@ public function addAction()
         $form = new ApiTransportForm();
         $form->on(ApiTransportForm::ON_SUCCESS, function (ApiTransportForm $form) {
             (new CommandTransportConfig())->insert('transport', $form->getValues());
+
+            Notification::success(t('Command transport created successfully'));
```
Comment (nilmerg) [inline application/controllers/CommandTransportController.php:87]: `Created command transport successfully`

File: application/controllers/CommandTransportController.php [hunk 3]
```diff
@@ -103,6 +109,8 @@ public function removeAction()
                 Filter::where('name', $transportName)
             );
 
+            Notification::success(sprintf(t('Command transport "%s" removed successfully'), $transportName));
```
Comment (nilmerg) [inline application/controllers/CommandTransportController.php:112]: `Removed command transport "%s" successfully`

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php [hunk 4]
```diff
@@ -37,6 +45,13 @@ public function __construct($featureStatus)
         ];
 
         $this->getAttributes()->add('class', 'instance-features');
+
+        $this->on(self::ON_SUCCESS, function () {
+            $status = $this->submittedFeature->getEnabled() ? 'enabled' : 'disabled';
+            $label = $this->features[$this->submittedFeature->getFeature()];
+
+            Notification::success(sprintf(t('%s %s successfully'), $label, $status));
```
Comment (nilmerg) [inline application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:53]: `Enabled active checks successfully`, `Disabled active checks successfully`. One for each feature and state, both must be a literal in the message otherwise it cannot be translated.

Also, there may be multiple features toggled at the same time. Currently only for the last command the notification is shown. It's not possible to toggle multiple features at the same time via the UI, but the implementation already supports that in case we have a API some time where this will in fact be possible. So please also consider this when registering notifications.

File: application/forms/Command/Object/ToggleObjectFeaturesForm.php [hunk 5]
```diff
@@ -47,6 +55,13 @@ public function __construct($featureStatus)
         ];
 
         $this->getAttributes()->add('class', 'object-features');
+
+        $this->on(self::ON_SUCCESS, function () {
+            $status = $this->submittedFeature->getEnabled() ? 'enabled' : 'disabled';
+            $label = $this->features[$this->submittedFeature->getFeature()]['label'];
+
+            Notification::success(sprintf(t('%s %s successfully'), $label, $status));
```
Comment (nilmerg) [inline application/forms/Command/Object/ToggleObjectFeaturesForm.php:63]: * `Enabled active checks successfully`, `Disabled active checks successfully`, ...
* Support for multiple notifications

File: application/forms/Command/Object/AcknowledgeProblemForm.php [hunk 6]
```diff
@@ -21,6 +22,17 @@ class AcknowledgeProblemForm extends CommandForm
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            Notification::success(tp(
+                'Acknowledged a problem successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/AcknowledgeProblemForm.php:29]: `Acknowledged problem successfully`. Note the missing `a`. It's not just *some* problem, it's *the* problem the user acknowledged just now.

File: application/forms/Command/Object/AcknowledgeProblemForm.php [hunk 7]
```diff
@@ -21,6 +22,17 @@ class AcknowledgeProblemForm extends CommandForm
...
+                'Acknowledged problems successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/AcknowledgeProblemForm.php:30]: We know the count, why not include it in the message?

File: application/forms/Command/Object/AddCommentForm.php [hunk 8]
```diff
@@ -21,6 +22,15 @@ class AddCommentForm extends CommandForm
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            Notification::success(
+                tp('Added a comment successfully', 'Added comments successfully', count($this->getObjects()))
```
Comment (nilmerg) [inline application/forms/Command/Object/AddCommentForm.php:29]: * `Added comment successfully` as singular version
* Include count of objects in plural version
* Rephrase plural version to `Added comment successfully to %d hosts` for hosts (for services `Added comment successfully to %d services`)
  It's the same comment on every host/service.

Please adjust all other messages I didn't comment regarding this the same way.

File: application/forms/Command/Object/ProcessCheckResultForm.php [hunk 9]
```diff
@@ -19,6 +20,17 @@ class ProcessCheckResultForm extends CommandForm
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            Notification::success(tp(
+                'Passive Check Result submitted successfully',
+                'Passive Check Results submitted successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/ProcessCheckResultForm.php:28]: Put `Submitted` in front.

File: application/forms/Command/Object/ScheduleCheckForm.php [hunk 10]
```diff
@@ -20,6 +21,17 @@ class ScheduleCheckForm extends CommandForm
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            Notification::success(tp(
+                'Schedule a check successfully',
+                'Schedule checks successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleCheckForm.php:29]: `Scheduled`

File: application/forms/Command/Object/ScheduleHostDowntimeForm.php [hunk 11]
```diff
@@ -35,6 +36,14 @@ public function __construct()
 
         $flexibleDuration = $config->get('settings', 'hostdowntime_flexible_duration', 'PT2H');
         $this->flexibleDuration = new DateInterval($flexibleDuration);
+
+        $this->on(self::ON_SUCCESS, function () {
+            Notification::success(tp(
+                'Downtime scheduled successfully',
+                'Downtimes scheduled successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleHostDowntimeForm.php:43]: Put `Scheduled` in front. I know I've told you otherwise in chat, but I think now this sounds better.

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 12]
```diff
@@ -57,6 +58,14 @@ public function __construct()
 
         $flexibleDuration = $config->get('settings', 'servicedowntime_flexible_duration', 'PT2H');
         $this->flexibleDuration = new DateInterval($flexibleDuration);
+
+        $this->on(self::ON_SUCCESS, function () {
+            Notification::success(tp(
+                'Downtime scheduled successfully',
+                'Downtimes scheduled successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:65]: Put `Scheduled` in front.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php [hunk 13]
```diff
@@ -18,6 +19,13 @@ class ToggleInstanceFeaturesForm extends CommandForm
 
     protected $featureStatus;
 
+    /**
+     * ToggleFeature(s) being used to submit this form
+     *
+     * @var ToggleInstanceFeatureCommand
```
Comment (nilmerg) [inline application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:25]: It's an array and `ToggleInstanceFeatureCommand[]` then.

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php [hunk 14]
```diff
@@ -37,6 +45,61 @@ public function __construct($featureStatus)
         ];
 
         $this->getAttributes()->add('class', 'instance-features');
+
+        $this->on(self::ON_SUCCESS, function () {
+            /** @var ToggleInstanceFeatureCommand $feature */
```
Comment (nilmerg) [inline application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:50]: Is this necessary with the updated type-hint above?

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php [hunk 15]
```diff
@@ -37,6 +45,61 @@ public function __construct($featureStatus)
...
+            foreach ($this->submittedFeatures as $feature) {
+                switch ($feature->getFeature()) {
+                    case ToggleInstanceFeatureCommand::FEATURE_ACTIVE_HOST_CHECKS:
+                        $message = tp(
+                            'Enabled active host checks successfully',
+                            'Disabled active host checks successfully',
+                            (int) $feature->getEnabled()
+                        );
```
Comment (nilmerg) [inline application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:58]: Mhm, what? Doesn't even work I suppose, does it? Don't use `tp` as control structure :wink:

File: application/forms/Command/Object/AcknowledgeProblemForm.php [hunk 16]
```diff
@@ -21,6 +23,23 @@ class AcknowledgeProblemForm extends CommandForm
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $objectsType = 'services';
+            if (current($this->getObjects()) instanceof Host) {
+                $objectsType = 'hosts';
```
Comment (nilmerg) [inline application/forms/Command/Object/AcknowledgeProblemForm.php:32]: No variables for translatable strings. Use this control structure to define the entire message.

Comment (nilmerg) [reply application/forms/Command/Object/AcknowledgeProblemForm.php:32]: Oh and please perform this differentiation everywhere (my preferred solution) or nowhere. Currently it's only done here.

File: application/forms/Command/Object/AddCommentForm.php [hunk 17]
```diff
@@ -21,6 +23,23 @@ class AddCommentForm extends CommandForm
...
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $objectsType = 'services';
+            if (current($this->getObjects()) instanceof Host) {
+                $objectsType = 'hosts';
+            }
+
+            Notification::success(sprintf(
+                tp('Added comment successfully', 'Added comments to %d %s successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/AddCommentForm.php:36]: `comment` for the plural version. It's the same comment. Yes, multiple versions of it, but that's already stated by using the plural for the target.

File: application/forms/Command/Object/AcknowledgeProblemForm.php [hunk 18]
```diff
@@ -21,6 +23,23 @@ class AcknowledgeProblemForm extends CommandForm
...
+            }
+
+            Notification::success(sprintf(
+                tp('Acknowledged problem successfully', 'Acknowledged problems to %d %s successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/AcknowledgeProblemForm.php:36]: `problem on` instead of `problems to`

File: application/forms/Command/Object/DeleteDowntimeForm.php [hunk 19]
```diff
@@ -18,6 +19,18 @@ class DeleteDowntimeForm extends CommandForm
 
     protected $defaultAttributes = ['class' => 'inline'];
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+
+            Notification::success(sprintf(
+                tp('Removed downtime successfully', 'Removed downtimes from %d objects successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/DeleteDowntimeForm.php:28]: `downtime` in both versions.

File: application/forms/Command/Object/ProcessCheckResultForm.php [hunk 20]
```diff
@@ -19,6 +20,23 @@ class ProcessCheckResultForm extends CommandForm
...
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $objectsType = 'services';
+            if (current($this->getObjects()) instanceof Host) {
+                $objectsType = 'hosts';
+            }
+
+            Notification::success(sprintf(tp(
+                'Submitted Passive Check Result successfully',
+                'Submitted Passive Check Results for %d %s successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/ProcessCheckResultForm.php:34]: Don't use capitalized words in messages. Use `result` instead in both versions.

File: application/forms/Command/Object/RemoveAcknowledgementForm.php [hunk 21]
```diff
@@ -7,13 +7,32 @@
...
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $objectsType = 'services';
+            if (current($this->getObjects()) instanceof Host) {
+                $objectsType = 'hosts';
+            }
+
+            Notification::success(sprintf(tp(
+                'Removed acknowledgement successfully',
+                'Removed acknowledgements from %d %s successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/RemoveAcknowledgementForm.php:30]: `acknowledgement` in both versions.

File: application/forms/Command/Object/ScheduleCheckForm.php [hunk 22]
```diff
@@ -20,6 +22,23 @@ class ScheduleCheckForm extends CommandForm
...
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $objectsType = 'services';
+            if (current($this->getObjects()) instanceof Host) {
+                $objectsType = 'hosts';
+            }
+
+            Notification::success(sprintf(
+                tp('Scheduled check successfully', 'Scheduled checks for %d %s successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleCheckForm.php:35]: `check` in both versions.

File: application/forms/Command/Object/ScheduleHostDowntimeForm.php [hunk 23]
```diff
@@ -35,6 +36,15 @@ public function __construct()
 
         $flexibleDuration = $config->get('settings', 'hostdowntime_flexible_duration', 'PT2H');
         $this->flexibleDuration = new DateInterval($flexibleDuration);
+
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+
+            Notification::success(sprintf(
+                tp('Scheduled downtime successfully', 'Scheduled downtimes for %d hosts successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleHostDowntimeForm.php:44]: `downtime` in both versions.

File: application/forms/Command/Object/ScheduleServiceDowntimeForm.php [hunk 24]
```diff
@@ -57,6 +58,15 @@ public function __construct()
 
         $flexibleDuration = $config->get('settings', 'servicedowntime_flexible_duration', 'PT2H');
         $this->flexibleDuration = new DateInterval($flexibleDuration);
+
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+
+            Notification::success(sprintf(
+                tp('Scheduled downtime successfully', 'Scheduled downtimes for %d services successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/ScheduleServiceDowntimeForm.php:66]: `downtime` in both versions.

File: application/forms/Command/Object/SendCustomNotificationForm.php [hunk 25]
```diff
@@ -19,6 +21,23 @@ class SendCustomNotificationForm extends CommandForm
...
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $objectsType = 'services';
+            if (current($this->getObjects()) instanceof Host) {
+                $objectsType = 'hosts';
+            }
+
+            Notification::success(sprintf(tp(
+                'Sent custom notification successfully',
+                'Sent custom notifications for %d %s successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/SendCustomNotificationForm.php:35]: `notification` for both versions.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php (hunk 14 above)
Comment (Yonas-net) [reply application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:50]: No.

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php (hunk 15 above)
Comment (Yonas-net) [reply application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:58]: Sure, it does work. Don't know what the problem is, I am passing the states as int, this isn't a control structure.

File: application/forms/Command/Object/AcknowledgeProblemForm.php (hunk 16 above)
Comment (Yonas-net) [reply application/forms/Command/Object/AcknowledgeProblemForm.php:32]: Not sure 🤔 whether you''ve seen it in hindsight but have used it pretty much everywhere I can.

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php (hunk 15 above)
Comment (nilmerg) [reply application/forms/Command/Instance/ToggleInstanceFeaturesForm.php]: It is. `tp` means `translatePlural` and is used to designate different message versions. One for singular and one for plural. You use it to choose two entirely different messages. That's a mis-use of `tp`.

File: application/forms/Command/Object/AcknowledgeProblemForm.php [hunk 26]
```diff
@@ -21,6 +23,27 @@ class AcknowledgeProblemForm extends CommandForm
...
+                'Acknowledged problem on %d services successfully',
+                $countObjects
+            ), $countObjects);
+            if (current($this->getObjects()) instanceof Host) {
+                $message = sprintf(tp(
+                    'Acknowledged problem successfully',
+                    'Acknowledged problem on %d hosts successfully',
+                    $countObjects
+                ), $countObjects);
+            }
```
Comment (nilmerg) [inline application/forms/Command/Object/AcknowledgeProblemForm.php:41]: This way the message for services is defined always. Why not an `if ... else`?

File: application/forms/Command/Object/AddCommentForm.php [hunk 27]
```diff
@@ -21,6 +23,25 @@ class AddCommentForm extends CommandForm
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $message = sprintf(
+                tp('Added comment successfully', 'Added comments to %d services successfully', $countObjects),
```
Comment (nilmerg) [inline application/forms/Command/Object/AddCommentForm.php:31]: Here it's still `comments` instead of `comment`

File: application/forms/Command/Object/RemoveAcknowledgementForm.php [hunk 28]
```diff
@@ -7,13 +7,36 @@
...
 {
     use Auth;
 
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $message = sprintf(tp(
+                'Removed acknowledgment successfully',
+                'Removed acknowledgment problem from %d services successfully',
```
Comment (nilmerg) [inline application/forms/Command/Object/RemoveAcknowledgementForm.php:25]: What is a `acknowledgment problem`? Where does `problem` come from? This is of course an *acknowledged problem* that is getting un-acknowledged here, but it's the acknowledgement that's removed, not the problem.

**Review by nilmerg — CHANGES_REQUESTED** [review]
`tp` in the toggle feature form is also still mis-used as noted above.

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php [hunk 29]
```diff
@@ -37,6 +45,61 @@ public function __construct($featureStatus)
...
+        $this->on(self::ON_SUCCESS, function () {
+            foreach ($this->submittedFeatures as $feature) {
+                $enabled = $feature->getEnabled();
+                switch ($feature->getFeature()) {
+                    case ToggleInstanceFeatureCommand::FEATURE_ACTIVE_HOST_CHECKS:
+                        if ($enabled) {
+                            $message = t('Enabled active host checks successfully');
+                        } else {
+                            $message = t('Disabled active host checks successfully');
+                        }
```
Comment (nilmerg) [inline application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:58]: Empty lines after control structures are a requirement here, though. :wink:

File: application/forms/Command/Instance/ToggleInstanceFeaturesForm.php [hunk 30]
```diff
@@ -37,6 +45,61 @@ public function __construct($featureStatus)
...
+                        } else {
+                            $message = t('Disabled notifications successfully');
+                        }
+                        break;
+                    case ToggleInstanceFeatureCommand::FEATURE_PERFORMANCE_DATA:
+                        if ($enabled) {
+                            $message = t('Enabled performance data successfully');
+                        } else {
+                            $message = t('Disabled performance data successfully');
+                        };
```
Comment (nilmerg) [inline application/forms/Command/Instance/ToggleInstanceFeaturesForm.php:93]: What's this semicolon?

File: application/forms/Command/Object/RemoveAcknowledgementForm.php [hunk 31]
```diff
@@ -7,13 +7,36 @@
...
+    public function __construct()
+    {
+        $this->on(self::ON_SUCCESS, function () {
+            $countObjects = count($this->getObjects());
+            $message = sprintf(tp(
+                'Removed acknowledgment successfully',
+                'Removed acknowledgment from %d services successfully',
+                $countObjects
+            ), $countObjects);
+            if (current($this->getObjects()) instanceof Host) {
```
Comment (nilmerg) [inline application/forms/Command/Object/RemoveAcknowledgementForm.php:28]: There's no `else` yet.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
