### PR TITLE
Controller: Reset all params on form change

### LINKED ISSUE #318: Clearing the searchbar in the tactical overview doesn't update URL
## Describe the bug
Clearing the filter using the searchbar, the url isn't updated and after the next autorefresh the filter re-appears.

## Expected behavior
The url is updated and the filter doesn't re-appear.

### PR DESCRIPTION
**Pull request by Yonas-net**
The problem here was all the parameters added by the search-bar could never be deleted again as
the tactical overview doesn't provide any preserved params that could reset this filter.
This PR fixes that by simply removing all parameters from the URL being redirected when the trash icon is pressed.

resolves #318

### CODE REVIEW

**Comment by nilmerg** [comment]
But that defeats the purpose of preserving parameters.

**Review by nilmerg — CHANGES_REQUESTED** [review]
Changing a term also doesn't clear it but re-adds it. e.g. Changing `host.name=foo` to `host.name=bar` will result in `?host.name=foo&host.name=bar`.

**Review by nilmerg — CHANGES_REQUESTED** [review]
It works fine now. But it's still too complicated. Isn't the problem that the redirect url still contains params even if none need to be preserved? I'd try to solve that instead.

File: library/Icingadb/Web/Controller.php [hunk 1]
```diff
@@ -154,7 +154,7 @@ public function createSortControl(Query $query, array $columns)
     public function createSearchBar(Query $query, array $preserveParams = null)
     {
         $requestUrl = Url::fromRequest();
-        $redirectUrl = $preserveParams !== null ? $requestUrl->onlyWith($preserveParams) : $requestUrl;
+        $redirectUrl = $preserveParams !== null ? $requestUrl->onlyWith($preserveParams) : $requestUrl->setParams([]);
```
Comment (nilmerg) [inline library/Icingadb/Web/Controller.php:157]: Way better already :smile: But `onlyWith` clones the url first, `setParams` does not. But the cloning should happen because changing the request url implicitly isn't good.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
LGTM :)
