### PR TITLE
Macros: Add missing support for `DateTime` type macro

### LINKED ISSUE #1111: Some macros can not be resolved in action URLs
## Describe the bug

Using `$host.state.last_state_change$` macro for action URLs breaks the detail view of affected hosts with the following error message:

```
Icinga\Module\Icingadb\Web\Navigation\Action::resolveMacro(): Return value must be of type string, DateTime returned

```

## To Reproduce

1. Creat a new Navigation Item of the type "Host Action" or "Service Action"
2. Use the macro `$host.state.last_state_change$` in the `URL` field
3. Open detail view of affected Host or Service

## Your Environment

* Icinga Web version: 2.12.1
* Icinga DB Web version: 1.1.3

## Additional context

ref/IP/56978

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #1111

### CODE REVIEW

File: library/Icingadb/Common/Macros.php [hunk 1]
```diff
@@ -120,6 +121,12 @@ public function resolveMacro(string $macro, $object): string
...
         }
 
-        return $value !== null ? $value : $macro;
+        if ($value instanceof DateTime) {
+            $value = $value->getTimestamp();
+        } elseif (is_bool($value)) {
+            $value = $value ? 'y' : 'n';
+        }
+
+        return $value ?? $macro;
```
Comment (nilmerg) [inline library/Icingadb/Common/Macros.php:130]: Cast to string here, it might still be an int or float I assume.

Comment (sukhwinder33445) [reply library/Icingadb/Common/Macros.php:130]: The specified return type of the function is responsible for the cast.

Comment (nilmerg) [reply library/Icingadb/Common/Macros.php:130]: Hm, yeah, as if [implicit type conversion did never turn out to be an issue](https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string).

Explicit is better than implicit.

**Review by nilmerg — APPROVED** [review]
