### PR TITLE
Models: Use `MillisecondTimestamp` instead of `Timestamp` behavior

### LINKED ISSUE #740: Timestamp comparison is broken somewhere (at least in Postgres)
## Describe the bug
If try to add a filter for "last state change", pick the "=" operator and try one of the suggestested options, I get a stracktrace with `SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "1.606606469816E+15"`.

```
#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(402): PDOStatement->execute()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec()
#2 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(684): ipl\Sql\Connection->select()
#3 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(142): ipl\Orm\Query->yieldResults()
#4 [internal function]: ipl\Orm\ResultSet->yieldTraversable()
#5 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(122): Generator->valid()
#6 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(69): ipl\Orm\ResultSet->advance()
#7 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(656): ipl\Orm\ResultSet->current()
#8 /usr/share/icingaweb2/modules/icingadb/application/controllers/ServicesController.php(134): ipl\Orm\Query->first()
#9 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(492): Icinga\Module\Icingadb\Controllers\ServicesController->indexAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

## To Reproduce
See above

## Expected behavior
Get the one service where this actually applies and no stacktrace.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2 
* Icinga Web 2 version (System - About): 2.11.4
* Web browser: firefox
* 
* Icinga DB version (`icingadb --version`): Icinga DB version: v1.1.0
* PHP version used (`php --version`): PHP 7.4.33 (cli) (built: Feb 22 2023 20:07:47) ( NTS )
* Server operating system and version: Debian 11 (bullseye) mostly

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #740

### CODE REVIEW

File: library/Icingadb/Widget/Detail/CheckStatistics.php [hunk 1]
```diff
@@ -115,8 +115,8 @@ protected function assembleBody(BaseHtmlElement $body)
             Html::tag(
                 'div',
                 ['class' => 'bubble upwards'],
-                new VerticalKeyValue(t('Last update'), $this->object->state->last_update !== null
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/CheckStatistics.php:118]: same here

File: library/Icingadb/Widget/Detail/CommentDetail.php [hunk 2]
```diff
@@ -73,20 +73,20 @@ protected function createDetails(): array
...
-                DateFormatter::formatDateTime($this->comment->entry_time)
+                DateFormatter::formatDateTime($this->comment->entry_time->getTimestamp())
             );
-            $details[] = new HorizontalKeyValue(t('Expires'), $this->comment->expire_time != 0
-                ? DateFormatter::formatDateTime($this->comment->expire_time)
+            $details[] = new HorizontalKeyValue(t('Expires'), $this->comment->expire_time
+                ? DateFormatter::formatDateTime($this->comment->expire_time->getTimestamp())
                 : t('Never'));
         } else {
-            if ($this->comment->expire_time != 0) {
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/CommentDetail.php:82]: Do you have an idea why this is a non-strict comparison? Have you verified that removing it still has the same effect?

**Previously:**
NULL != 0 (false)
0 != 0 (false)
'' != 0 (false)
1 != 0 (true)

**Now:**
NULL (false)
DateTime (true)

Though, DateTime can also be `1970-01-01T00:00:00` (which is the result of `0`) and that evaluates to true now, instead of false.

You could adjust it to `!== null`, but only if `expire_time` can never be just `0`. (which would indicate that this comparison is outdated)

File: library/Icingadb/Widget/Detail/DowntimeCard.php [hunk 3]
```diff
@@ -25,13 +25,13 @@ public function __construct(Downtime $downtime)
     {
         $this->downtime = $downtime;
 
-        $this->start = $this->downtime->scheduled_start_time;
-        $this->end = $this->downtime->scheduled_end_time;
+        $this->start = $this->downtime->scheduled_start_time->getTimestamp();
+        $this->end = $this->downtime->scheduled_end_time->getTimestamp();
 
-        if ($this->downtime->end_time > $this->downtime->scheduled_end_time) {
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/DowntimeCard.php:31]: You don't have to change this. `DateTime` objects are comparable.

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 4]
```diff
@@ -319,37 +325,49 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
+            DateFormatter::formatDateTime($downtime->end_time->getTimestamp())
         );
-        $eventInfo[] = new HorizontalKeyValue(t('Actual End'), DateFormatter::formatDateTime($downtime->end_time));
 
         if ($downtime->is_flexible) {
             $eventInfo[] = new HorizontalKeyValue(t('Flexible'), t('Yes'));
             $eventInfo[] = new HorizontalKeyValue(
                 t('Duration'),
-                DateFormatter::formatDuration($downtime->flexible_duration)
+                DateFormatter::formatDuration($downtime->flexible_duration->getTimestamp())
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:359]: This doesn't take a timestamp!

**Review by nilmerg — CHANGES_REQUESTED** [review]
Visiting `/icingaweb2/icingadb/hosts?columns=host.state.next_update` shows:

```
Object of class DateTime could not be converted to int

#0 /usr/local/src/ipl-web/src/Widget/TimeUntil.php(19): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer)
#1 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Widget/ItemTable/StateRowItem.php(100): ipl\Web\Widget\TimeUntil->__construct(Object(DateTime))
#2 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Widget/ItemTable/HostRowItem.php(48): Icinga\Module\Icingadb\Widget\ItemTable\StateRowItem->assembleCell(Object(ipl\Html\HtmlElement), String, Object(DateTime))
#3 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Widget/ItemTable/BaseRowItem.php(100): Icinga\Module\Icingadb\Widget\ItemTable\HostRowItem->assembleCell(Object(ipl\Html\HtmlElement), String, Object(DateTime))
#4 /usr/local/src/ipl-html/src/HtmlDocument.php(294): Icinga\Module\Icingadb\Widget\ItemTable\BaseRowItem->assemble()
...
```

File: library/Icingadb/Widget/Detail/EventDetail.php (hunk 4 above)
Comment (sukhwinder33445) [reply library/Icingadb/Widget/Detail/EventDetail.php:359]: `getTimestamp()` returns the seconds as expected.

File: library/Icingadb/Widget/Detail/CommentDetail.php (hunk 2 above)
Comment (nilmerg) [reply library/Icingadb/Widget/Detail/CommentDetail.php:82]: Okay, verified that this cannot happen anymore. `!== null` is sufficient.

File: library/Icingadb/Model/State.php [hunk 5]
```diff
@@ -64,7 +64,7 @@ public function createBehaviors(Behaviors $behaviors)
             'in_downtime'
         ]));
 
-        $behaviors->add(new Timestamp([
+        $behaviors->add(new MillisecondTimestamp([
             'execution_time',
             'latency',
```
Comment (nilmerg) [inline library/Icingadb/Model/State.php:69]: not a timestamp as well!

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Comment by nilmerg** [comment]
This only fixes the exception. The suggestions are still incorrect.
