### PR TITLE
HostController: Add `sortControl` to services tab of host detail

### LINKED ISSUE #295: Add sort control for services in host detail view
## Describe the bug
It would be nice to have a sort control for the `Services` tab in the host detail view to sort the services as needed.
A search bar can also be added.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
resolves #295

### CODE REVIEW

File: application/controllers/HostController.php [hunk 1]
```diff
@@ -184,6 +184,15 @@ public function servicesAction()
         $limitControl = $this->createLimitControl();
         $paginationControl = $this->createPaginationControl($services);
         $viewModeSwitcher = $this->createViewModeSwitcher($paginationControl, $limitControl);
+        $sortControl = $this->createSortControl(
+            $services,
+            [
+                'service.display_name, host.display_name' => t('Name'),
```
Comment (nilmerg) [inline application/controllers/HostController.php:190]: Remove `host.display_name`. It's redundant since all the services belong to the same host.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
