### PR TITLE
Use EventDetailExtentionHook in EventDetail

### LINKED ISSUE #270: Hook `EventDetailExtension` is not used
## Describe the bug
Providing implementations for the hook `Icingadb\EventDetailExtension` has no effect.

## Expected behavior
The `EventDetail` should incorporate extensions provided by modules.

## Additional context
#232

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fix #270

### CODE REVIEW

**Review by nilmerg — CHANGES_REQUESTED** [review]
Sorry but that's wrong. There's literally no reason why a placement of extensions is even necessary the way it's structured now. You have only a single area now. This area however is still separated in multiple blocks. Notifications for example have three: Output, Event Info, Notified users

A hook may want to place it's content between output and the info, at the moment this isn't possible.

**Comment by sukhwinder33445** [comment]
I see. You mean I should add each part into a function like `createComment()`, `createOutput()`? That way it will be the same as `UsergroupDetail` class, and we can add extensions between with array key.

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 1]
```diff
@@ -141,19 +143,24 @@ protected function assembleNotificationEvent(NotificationHistory $notification)
...
+            $notifiedUsers[] = new UserList($users);
+            $notifiedUsers[] = (new ShowMore(
+                $users,
+                Links::users()->addParams(['notification_history.id' => bin2hex($notification->id)]),
+                sprintf(t('Show all %d recipients'), $notification->users_notified)
+            ))->setBaseTarget('_next');
         }
+
+        $this->add(ObjectDetailExtensionHook::injectExtensions([
+            100 => $pluginOutput,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:155]: The output section is at `0`. `100` is the graph section. Take a look at `BaseExtensionHook::BASE_LOCATIONS` and subtract 1000 of each.

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 2]
```diff
@@ -141,19 +143,24 @@ protected function assembleNotificationEvent(NotificationHistory $notification)
...
+            200 => $eventInfo,
+            300 => $notifiedUsers
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:157]: That'd be `500`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 3]
```diff
@@ -199,39 +206,50 @@ protected function assembleStateChangeEvent(StateHistory $stateChange)
...
+        );
+
+        $eventInfo[] = new HorizontalKeyValue(
+            t('State Type'),
+            $stateChange->state_type === 'hard' ? t('Hard', 'state') : t('Soft', 'state')
         );
+
+        $eventInfo[] = new HorizontalKeyValue($objectKey, $objectInfo);
+
+
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:238]: Why two empty lines? To set it off of the single ones above? Why they're there? Empty lines are only mandatory after control structures, *most* others are personal style (I doubt that it is that, because in the method below there are none), but two or more subsequent empty lines are discouraged.

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 4]
```diff
@@ -199,39 +206,50 @@ protected function assembleStateChangeEvent(StateHistory $stateChange)
...
+        $this->add(ObjectDetailExtensionHook::injectExtensions([
+            100 => $pluginOutput,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:240]: That'd be `0`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 5]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
                 new HtmlElement('h2', null, Text::create(t('This downtime has been cancelled'))),
                 new HorizontalKeyValue(t('Cancelled On'), DateFormatter::formatDateTime($downtime->cancel_time)),
                 new HorizontalKeyValue(t('Cancelled by'), [new Icon('user'), $downtime->cancelled_by])
-            );
+            ];
         }
+
+
+        $this->add(ObjectDetailExtensionHook::injectExtensions([
+            100 => $commentInfo,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:338]: That'd be 200.

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 6]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
+            200 => $eventInfo,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:339]: And that `201`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 7]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
+            300 => $cancelInfo
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:340]: That'd be `600`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 8]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
-                    new HorizontalKeyValue(t('Expired On'), DateFormatter::formatDateTime($comment->remove_time))
+                $removedInfo[] = new HorizontalKeyValue(
+                    t('Expired On'),
+                    DateFormatter::formatDateTime($comment->remove_time)
                 );
             }
         }
+
+        $this->add(ObjectDetailExtensionHook::injectExtensions([
+            100 => $commentInfo,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:406]: That'd be `200`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 9]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
+            200 => $eventInfo,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:407]: And that `201`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 10]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
+            300 => $tiedToAckInfo,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:408]: I'd identify that as *related* information, as such it should be `500`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 11]
```diff
@@ -261,115 +279,140 @@ protected function assembleDowntimeEvent(DowntimeHistory $downtime)
...
+            400 => $removedInfo
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:409]: That'd be `600`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 12]
```diff
@@ -387,35 +430,38 @@ protected function assembleFlappingEvent(FlappingHistory $flapping)
...
+            $eventInfo[] = new HorizontalKeyValue(t('Ended on'), DateFormatter::formatDateTime($flapping->end_time));
+            $eventInfo[] = new HorizontalKeyValue(t('Reason'), sprintf(
+                t('State change rate of %.2f%% undercut the threshold (%.2f%%)'),
+                $flapping->percent_state_change_end,
+                $flapping->flapping_threshold_low
+            ));
         }
+
+        $this->add(ObjectDetailExtensionHook::injectExtensions([
+            100 => $eventInfo
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:450]: That'd be `200`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 13]
```diff
@@ -460,36 +512,42 @@ protected function assembleAcknowledgeEvent(AcknowledgementHistory $acknowledgem
...
+                                ? t('Host recovered') // Hosts have no other state between UP and DOWN
+                                : t('Service changed its state')
                         );
                     }
                 }
             }
         }
+
+        $this->add(ObjectDetailExtensionHook::injectExtensions([
+            100 => $commentInfo,
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:543]: That'd be `200`

File: library/Icingadb/Widget/Detail/EventDetail.php [hunk 14]
```diff
@@ -460,36 +512,42 @@ protected function assembleAcknowledgeEvent(AcknowledgementHistory $acknowledgem
...
+            200 => $eventInfo
```
Comment (nilmerg) [inline library/Icingadb/Widget/Detail/EventDetail.php:544]: And that `201`

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: library/Icingadb/Widget/Detail/EventDetail.php (hunk 3 above)
Comment (sukhwinder33445) [reply library/Icingadb/Widget/Detail/EventDetail.php:238]: That was a mistake, I just wanted to add a new line.

**Review by nilmerg — APPROVED** [review]
